language: php

notifications:
  email:
    on_success: never
    on_failure: change

# Cache composer
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - WP_VERSION=4.6 WP_MULTISITE=0

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1

install:
  - composer install --no-interaction --prefer-source
  - npm install -g bower
  - bower install

before_script:
  - bash bin/install-wp-tests.sh wordpress_test_asu_rfi root '' localhost $WP_VERSION
  - vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs/

script:
  - phpunit  --coverage-clover coverage/clover.xml
  - ./vendor/bin/phpcs --standard=.phpcs-ruleset.xml src
